apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

namespace: default

images:
- name: go-example-argocd
  newName: danielvincenzi/go-example-argocd
  newTag: c20c18f1cfbfc8b9e3303711b17f0e9b04cf1a6f
