apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- rollout.yaml
- service.yaml
- service_preview.yaml

namespace: default

images:
- name: go-example-argocd
  newName: 260712519057.dkr.ecr.us-east-1.amazonaws.com/go-example-argocd
  newTag: 94b0fd1b9d25563419486b79eae77be9ef39094b
