name: Deployment
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Build
        uses: docker/login-action@v1
        with:
          username: danielvincenzi
          password: ${{ secrets.DOCKER_ACCESS_TOKEN}}
      
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          # repository: danielvincenzi/go-example-argocd
          tags: ${{ github.sha }}, latest