name: Deployment
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
          repository: danielvincenzi/go-example-argocd
          tags: ${{ github.sha }}, latest

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Kustomize
        uses: imranismail/setup-kustomize@v1

      - name: Update Kubernetes
        run: |
          cd kubernetes
          kustomize edit set image go-example-argocd=danielvincenzi/go-example-argocd:${{ github.sha }}
          cat kustomization.yaml

      - name: Commit
        run: |
          git config --local user.name 'GitHub Actions'
          git add .
          git commit -m 'Set image tag to `${{ github.sha }}`'

      - name: Push
        uses: ad-m/github-push-action@master

