name: Release workflow

on:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      # - "docs/**"
      - "terraform/**"

jobs:
  # build:
  #   name: Build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: checkout
  #       uses: actions/checkout@v2

  #     - name: Build and push Docker image
  #       uses: docker/build-push-action@v1
  #       with:
  #         username: ${{ secrets.DOCKER_USERNAME }}
  #         password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
  #         repository: danielvincenzi/go-example-argocd
  #         tags: ${{ github.sha }}, latest
  build:
    name: Build Docker image
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          # aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          # aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-session-name: GitHubActions

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: go-example-argocd
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t ${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG} .
          docker push ${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}

  sync:
    name: Trigger ArgoCD sync
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Kustomize
        uses: imranismail/setup-kustomize@v1

      - name: Update manifests to new version
        working-directory: "kubernetes/"
        run: |
          kustomize edit set image go-example-argocd=260712519057.dkr.ecr.us-east-1.amazonaws.com/go-example-argocd:${{ github.sha }}

      - name: Commit changes
        run: |
          git config --local user.name 'github-actions[ bot ]'
          git add .
          git commit -m 'Trigger sync on ArgoCD @ `${{ github.sha }}`'

      - name: Push
        uses: ad-m/github-push-action@master

